name: doan_tmdt
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6




  image_picker: ^0.8.9
  # thư viện đưa ảnh lên sever
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  crypto: ^3.0.1
  intl: ^0.19.0
  syncfusion_flutter_charts: ^21.2.4
  carousel_slider: ^4.2.1
  
  
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"



  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #- assets/img/logo1.png
    - assets/img/logoapp.png
    - assets/img/facebook.png
    - assets/img/google.png
    - assets/img/logo.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
